-- Safari tab keys
hs.hotkey.bind({ "cmd", "alt" }, "1", function()
    hs.osascript.applescript('tell front window of app "Safari" to set current tab to tab 1')
end)
hs.hotkey.bind({ "cmd", "alt" }, "2", function()
    hs.osascript.applescript('tell front window of app "Safari" to set current tab to tab 2')
end)
hs.hotkey.bind({ "cmd", "alt" }, "3", function()
    hs.osascript.applescript('tell front window of app "Safari" to set current tab to tab 3')
end)
hs.hotkey.bind({ "cmd", "alt" }, "4", function()
    hs.osascript.applescript('tell front window of app "Safari" to set current tab to tab 4')
end)
hs.hotkey.bind({ "cmd", "alt" }, "5", function()
    hs.osascript.applescript('tell front window of app "Safari" to set current tab to tab 5')
end)
hs.hotkey.bind({ "cmd", "alt" }, "6", function()
    hs.osascript.applescript('tell front window of app "Safari" to set current tab to tab 6')
end)
hs.hotkey.bind({ "cmd", "alt" }, "7", function()
    hs.osascript.applescript('tell front window of app "Safari" to set current tab to tab 7')
end)
hs.hotkey.bind({ "cmd", "alt" }, "8", function()
    hs.osascript.applescript('tell front window of app "Safari" to set current tab to tab 8')
end)
hs.hotkey.bind({ "cmd", "alt" }, "9", function()
    hs.osascript.applescript('tell front window of app "Safari" to set current tab to tab 9')
end)
